### ISSUE TITLE
Incorrect link in README.md

### ISSUE THREAD

**Issue by janmikaelr** [Aalto-LeTech/a-plus-rst-tools#2]
The git clone link for mooc-grader-rst-course repository provided in the README.md is incorrect and gives the following error message:

```
$ git clone --recursive https://github.com/Aalto-LeTech/mooc-grader-rst-course.git
Cloning into 'mooc-grader-rst-course'...
remote: Repository not found.
fatal: repository 'https://github.com/Aalto-LeTech/mooc-grader-rst-course.git/' not found
```

I suggest creating a new link as follows (Note! It does not work yet):
`git clone --recursive https://github.com/Aalto-LeTech/mooc-grader-course-rst.git`

**Comment by teemulehtinen** [comment]
Fixed the example clone command to select the "rst" branch.
