### ISSUE TITLE
id-based URLs to example solutions

### ISSUE THREAD

**Issue by jaguarfi** [Aalto-LeTech/a-plus-rst-tools#78]
>**Migrated from Trello*

Currently I have to (I think) link like this from rst:

```
`example solution <../w04/ch04_en/w04_ch04_en_27/info/model/>`_ 
```

This very inconvenient when there are a lot of such links and exercise numbers change. Any of these would be better:

```
`example solution <../w04/ch04_en/w04_ch04_en_fixedprice/info/model/>`_
`example solution <../w04/ch04_en/fixedprice/info/model/>`_
`example solution <../fixedprice/info/model/>`_
```

(Also, is the "info" necessary for some reason? Not that I care much.)
(Also, could we use "solution" instead of "model"? Not that it's too important.)

**Duplicated** Issue #77

**Comment by raphendyr** [comment]
Duplicate
