### ISSUE TITLE
Annotated directives do not allow to use more than 9 annotations.

### ISSUE THREAD

**Issue by jaguarfi** [Aalto-LeTech/a-plus-rst-tools#84]

**Comment by jaguarfi** [comment]
In any case, maybe using more than nine annotations could be overkill.

**Comment by raphendyr** [comment]
@jaguarfi  Is this limitation documented? If not, it could be with a mention "split the example to multiple directives if you need more annotations" or such.

**Comment by Mankro** [comment]
Does the code expect a single-digit number and that's why only 9 annotations could be used?

**Comment by jaguarfi** [comment]
@raphendyr  I think this limitation is not documented anywhere, but I would need to check. In any case, I closed this issue because I thought that nobody, except me, wanted to use more than nine annotations. But, maybe we can reopen this issue and remove that restriction. I could take a look at how the directive works. Perhaps as @Mankro mentioned, the directive expects one single-digit.
